# Generated by Django 3.2.5 on 2021-07-24 04:36

from django.db import migrations, models
import django.db.models.deletion
import student.defaults
import student.validations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('Course_Code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Course_Subject', models.CharField(default='', max_length=20)),
                ('Course_Title', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Department_Name', models.CharField(max_length=30)),
                ('Department_Id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Date_Time', models.DateTimeField(auto_now=True)),
                ('Year_Of_Admission', models.IntegerField(default=student.defaults.Year_Admission)),
                ('First_Name', models.CharField(max_length=50)),
                ('Middle_Name', models.CharField(blank=True, max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Class', models.CharField(max_length=50)),
                ('Group', models.CharField(max_length=50)),
                ('Admission_Number', models.CharField(max_length=50)),
                ('Roll_Number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Date_of_Birth', models.CharField(help_text='YYYY-MM-DD', max_length=10)),
                ('Gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Others')], max_length=20)),
                ('Father_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Mother_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Guardian_Name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('Religion', models.CharField(max_length=50)),
                ('Nationality', models.CharField(max_length=50)),
                ('Aadhaar_Number', models.CharField(default='', max_length=50)),
                ('Mobile_Number', models.CharField(max_length=10, validators=[student.validations.Phone_Number])),
                ('Email_Id', models.EmailField(max_length=250)),
                ('Alternate_Mobile_Number', models.CharField(max_length=10, null=True, validators=[student.validations.Phone_Number])),
                ('Door_Number', models.CharField(help_text='Flat/Door/Block Number', max_length=20)),
                ('Premises', models.CharField(help_text='Name of the Premises/Building/Village', max_length=100)),
                ('Street', models.CharField(help_text='Street/Road/Post Office', max_length=100)),
                ('Area', models.CharField(default='', help_text='Area/Locality Details', max_length=50)),
                ('City', models.CharField(default='', max_length=50)),
                ('State', models.CharField(default='', max_length=50)),
                ('Country', models.CharField(default='', max_length=50)),
                ('Pin_Code', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('Teacher_Name', models.CharField(max_length=50)),
                ('Teacher_Id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Teacher_Mobile_Number', models.CharField(max_length=10, validators=[student.validations.Phone_Number])),
                ('Tecaher_Email_Id', models.EmailField(max_length=250)),
                ('Teacher_Department_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.department')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Certificates',
            fields=[
                ('Roll_Number_Certificate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student.student')),
                ('Student_Image', models.ImageField(upload_to='Images/')),
                ('Study_Of_Conduct', models.ImageField(help_text='Size should be less than 300 KB', upload_to='Images/', validators=[student.validations.Image_Size])),
                ('Transfer_Certificate', models.ImageField(help_text='Size should be less than 300 KB', upload_to='Images/', validators=[student.validations.Image_Size])),
                ('Tenth_Marks_Long_Memo', models.ImageField(help_text='Size should be less than 300 KB', upload_to='Images/', validators=[student.validations.Image_Size])),
                ('Intermediate_Marks_Short_Memo', models.ImageField(help_text='Size should be less than 300 KB', upload_to='Images/', validators=[student.validations.Image_Size])),
                ('Student_Signature', models.ImageField(help_text='Size should be less than 300 KB', upload_to='Images/', validators=[student.validations.Image_Size])),
            ],
        ),
        migrations.CreateModel(
            name='Valid_User_Student',
            fields=[
                ('valid_User_User_Name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student.student')),
                ('valid_User_Password', models.CharField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student.student'), max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Valid_User_Teacher',
            fields=[
                ('valid_User_User_Name_Teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student.teacher')),
                ('valid_User_Password_Teacher', models.CharField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student.teacher'), max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Time_Marks', models.DateTimeField(auto_now=True)),
                ('Semester', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=20)),
                ('Marks_Type', models.CharField(choices=[('1', 'I Internal'), ('2', 'II Internal'), ('3', 'Semester'), ('4', 'Assignment'), ('5', 'Attendance')], max_length=10)),
                ('Marks_Alloted', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Course_Code_Marks', models.ManyToManyField(to='student.Courses')),
                ('Roll_Number_Marks', models.ManyToManyField(to='student.Student')),
                ('Teacher_Id_Marks', models.ManyToManyField(to='student.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Time_Marks', models.DateTimeField(auto_now=True)),
                ('Semester', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=20)),
                ('Attendance_Date', models.CharField(choices=[('1', 'Present'), ('2', 'Absent'), ('3', 'Discontinued')], max_length=15)),
                ('Course_Code_Attendance', models.ManyToManyField(to='student.Courses')),
                ('Roll_Number_Attendance', models.ManyToManyField(to='student.Student')),
                ('Teacher_Id_Attendance', models.ManyToManyField(to='student.Teacher')),
            ],
        ),
    ]
