# Generated by Django 3.2.5 on 2021-07-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='Course_Title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
