# Generated by Django 3.2.5 on 2021-07-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_courses_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Area',
            field=models.CharField(blank=True, default='', help_text='Area/Locality Details', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='City',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='Street',
            field=models.CharField(blank=True, help_text='Street/Road/Post Office', max_length=100),
        ),
    ]
