# Generated by Django 3.2.4 on 2021-07-25 09:23

from django.db import migrations, models
import student.validations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210724_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Intermediate_Marks_Short_Memo',
            field=models.ImageField(default='', help_text='Size should be less than 300 KB', upload_to='Images/', validators=[student.validations.Image_Size]),
        ),
        migrations.AddField(
            model_name='student',
            name='Student_Image',
            field=models.ImageField(default='', upload_to='Images/'),
        ),
        migrations.AddField(
            model_name='student',
            name='Student_Signature',
            field=models.ImageField(default='', help_text='Size should be less than 300 KB', upload_to='Images/', validators=[student.validations.Image_Size]),
        ),
        migrations.AddField(
            model_name='student',
            name='Study_Of_Conduct',
            field=models.ImageField(default='', help_text='Size should be less than 300 KB', upload_to='Images/', validators=[student.validations.Image_Size]),
        ),
        migrations.AddField(
            model_name='student',
            name='Tenth_Marks_Long_Memo',
            field=models.ImageField(default='', help_text='Size should be less than 300 KB', upload_to='Images/', validators=[student.validations.Image_Size]),
        ),
        migrations.AddField(
            model_name='student',
            name='Transfer_Certificate',
            field=models.ImageField(default='', help_text='Size should be less than 300 KB', upload_to='Images/', validators=[student.validations.Image_Size]),
        ),
        migrations.DeleteModel(
            name='Student_Certificates',
        ),
    ]
