# Generated by Django 3.2.5 on 2021-07-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210727_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='valid_User_Password',
            field=models.CharField(default=models.CharField(max_length=50, primary_key=True, serialize=False), max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='valid_User_User_Name',
            field=models.CharField(default=models.CharField(max_length=50, primary_key=True, serialize=False), max_length=10),
        ),
    ]
