# Generated by Django 3.2.5 on 2021-07-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210727_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='valid_User_User_Name',
        ),
        migrations.AlterField(
            model_name='student',
            name='valid_User_Password',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
