# Generated by Django 3.2.5 on 2021-07-29 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20210727_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('Groups', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='valid_User_Password_Teacher',
            field=models.CharField(default='', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student_attendance',
            name='Attendance_Date',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Discontinued', 'Discontinued')], max_length=15),
        ),
        migrations.AlterField(
            model_name='student_marks',
            name='Marks_Type',
            field=models.CharField(choices=[('I Internal', 'I Internal'), ('II Internal', 'II Internal'), ('Semester', 'Semester'), ('Assignment', 'Assignment'), ('Attendance', 'Attendance')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Valid_User_Teacher',
        ),
        migrations.AlterField(
            model_name='student',
            name='Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.groups'),
        ),
    ]
