# Generated by Django 3.2.5 on 2021-07-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20210729_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='Groups_Type',
            field=models.CharField(choices=[('Arts', 'Arts'), ('Science', 'Science')], default='', max_length=10),
        ),
    ]
