# Generated by Django 3.2.5 on 2021-07-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_groups_groups_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='Class',
            field=models.CharField(default='', max_length=10),
        ),
    ]
