#Generated by Django 3.2.5 on 2021-08-16 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20210816_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_attendance',
            name='Course_Code_Attendance',
        ),
        migrations.AddField(
            model_name='student_attendance',
            name='Course_Code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='student.courses'),
        ),
        migrations.RemoveField(
            model_name='student_attendance',
            name='Roll_Number_Attendance',
        ),
        migrations.AddField(
            model_name='student_attendance',
            name='Roll_Number_Attendance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='student.student'),
        ),
        migrations.RemoveField(
            model_name='student_attendance',
            name='Teacher_Id_Attendance',
        ),
        migrations.AddField(
            model_name='student_attendance',
            name='Teacher_Id_Attendance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='student.teacher'),
        ),
    ]
