# Generated by Django 3.2.5 on 2021-08-16 10:41

from django.db import migrations, models
import django.db.models.deletion
import student.defaults


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20210816_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_attendance',
            name='Date_Time_Original',
            field=models.DateTimeField(default=student.defaults.Attendance_Submit),
        ),
        migrations.AlterField(
            model_name='student_attendance',
            name='Attendance_Date',
            field=models.CharField(choices=[('PRESENT', 'PRESENT'), ('ABSENT', 'ABSENT'), ('DISCONTINUED', 'DISCONTINUED')], max_length=15),
        ),
        migrations.AlterField(
            model_name='student_attendance',
            name='Course_Code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='student.courses'),
        ),
        migrations.AlterField(
            model_name='student_attendance',
            name='Roll_Number_Attendance',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='student.student'),
        ),
        migrations.AlterField(
            model_name='student_attendance',
            name='Teacher_Id_Attendance',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='student.teacher'),
        ),
    ]
