# Generated by Django 3.2.5 on 2021-08-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_auto_20210821_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_marks',
            name='Marks_Total',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='student_marks',
            name='Marks_Alloted',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
