# Generated by Django 3.2.5 on 2021-08-21 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_auto_20210821_0642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_marks',
            old_name='Course_Code_Marks',
            new_name='Course_Code',
        ),
    ]
