# Generated by Django 3.2.5 on 2021-09-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_rename_course_code_marks_student_marks_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_marks',
            name='Marks_Alloted',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
